name: Release

on:
  push:
    tags:
      - "v*" # vから始まるタグ（v1.0.0など）がプッシュされたら起動

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リリースを作成するために必要
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # コミット履歴から自動でリリースノートを作成
